services:
  mybamboo:
    image: mybamboo
    ports:
      - 8085:8085
      - 54663:54663
    volumes:
      - my-bamboo-vol:/var/atlassian/application-data/bamboo

  mypostgres:
    image: mypostgres
    ports:
      - 5432:5432
    volumes:
      - my-postgres-vol:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: mysecretpassword
    # command: su - postgres -c '/setup_bamboo.sh'

volumes:
  my-bamboo-vol:
  my-postgres-vol: